Update web api usage to v4
unblu/unblu-visitor-sso-sample pull request #5
Opened 2024-07-17 12:56 UTC by davideberlein

replace web api v3 calls with the v4 equivalent.

2024-07-17 13:02 UTC, jmini commented on src/main/resources/static/application.js
> +    return await fetch(this.unbluBaseUrl + '/rest/v4/authenticator/isAuthenticated', options)
I do not think that `authenticator/isAuthenticated` exists in v4

2024-07-17 13:07 UTC, gysel commented on src/main/resources/static/application.js
> +    return await fetch(this.unbluBaseUrl + '/rest/v4/authenticator/isAuthenticated', options)
At least it was removed from the API docs...

https://www.unblu.com/en/docs/latest/reference/unblu-web-api/#tag/Authenticator

2024-07-17 13:33 UTC, jmini requested changes
Please use v4 endpoints

2024-07-17 13:33 UTC, davideberlein commented on src/main/resources/static/application.js
> +    return await fetch(this.unbluBaseUrl + '/rest/v4/authenticator/isAuthenticated', options)
that's bad 😢 I knew I forget to do something... check if the v4 methods are still availible ;-)

2024-07-17 15:28 UTC, gysel approved these changes

2024-07-18 06:19 UTC, jmini approved these changes

2024-07-18 06:32 UTC, merged